kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golang:1.15
    commands:
      - apt update
      - apt install -y libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev
      - apt install libxi-dev libgl1-mesa-dev libasound2-dev
      - go test ./...