kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    pull: if-not-exists
    image: harbor.internal.teamyapp.com/internal/candy-client-test:latest
    commands:
      - go mod download
      - xvfb-run go test ./...
trigger:
  branch:
    - master
  event:
    - pull_request
image_pull_secrets:
  - dockerconfig
